//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Your Company Name")]
[assembly: AssemblyProduct("Locadora")]
[assembly: AssemblyCopyright("Copyright (c) Your Company Name (Year)")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.0.2009.1907")]
[assembly: AssemblyFileVersion("1.0.2009.1907")]


